name: midistems
description: "midistems - Separate audio into stems and extract MIDI."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Audio processing
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.0
  audio_session: ^0.1.18
  flutter_midi: ^1.1.0
  # FFI for Python integration
  ffi: ^2.1.0
  # File management
  path_provider: ^2.1.2
  file_picker: ^8.1.7
  filepicker_windows: ^2.1.4
  # State management
  provider: ^6.1.1
  # UI components
  flutter_bloc: ^9.0.0
  fl_chart: ^0.70.2
  # Desktop window management
  window_manager: ^0.4.3
  # URL handling
  url_launcher: ^6.2.4
  # Utilities
  uuid: ^4.3.3
  path: ^1.8.3
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^16.1.0

flutter:
  uses-material-design: true
